mongo:
  host: localhost
  port: 27017
  username: rtb
  password: trustno1
  auth_source: admin
  database: contests

authentication:
  rounds: 12
  issuer: www.example.com
  secret: mysecret

authorization:
  default_roles:
  - public:read
  admin_roles:
  - admin
  - user:read
  - user:write
  - post:read
  - post:write
  - comment:read
  - comment:write